Implement basic testing scaffolding and GitHub Action
datares/discord-bot pull request #10
Opened 2023-01-12 20:01 UTC by christopherm99

Part of #7, some first steps in implementing tests for this repo. 

### **IMPORTANT: `MONGO_PASSWORD` in `.env` MUST be updated to `MONGO_URI`**

2023-01-13 04:50 UTC, colinpcurtis commented
this looks good to me so far, but I think we should probably merge the graceful failures PR first just since this has breaking changes for that (tests would have to be updated).  Either way this is solid work and will be really pro level stuff.

2023-01-13 04:54 UTC, colinpcurtis requested changes

2023-01-13 04:54 UTC, colinpcurtis commented on commands/iam.js
> +    await db.collection("verification").insertOne(doc);
nit but these should be single quote to match rest of code

2023-01-13 04:54 UTC, colinpcurtis commented on commands/update_roles.js
> +    const data = await db.collection("users").findOne({user_id});
same as above

2023-01-13 04:54 UTC, colinpcurtis commented on commands/verify.js
> +    await db.collection("users").insertOne(doc);
here as well

2023-01-13 04:54 UTC, colinpcurtis commented on commands/verify.js
> +    const userVerification = await db.collection("verification").findOne(doc);
and here

2023-01-13 04:54 UTC, colinpcurtis commented on commands/verify.js
> +    await db.collection("verification").deleteOne(doc);
oop

2023-01-13 04:54 UTC, colinpcurtis commented on commands/whoami.js
> +    return await db.collection("users").findOne({user_id});
nice

2023-01-13 04:54 UTC, colinpcurtis commented on db.js
> +const db = client.db("datares-discord-bot");
here as well

2023-01-13 04:54 UTC, colinpcurtis commented on test/iam.test.js
> +
this is probably the best stuff in the PR, mocking SES and mongo is really pro level testing and will help a lot for development

2023-01-13 05:44 UTC, christopherm99 commented
The double quotes is a Prettier thing, happy to change it, but if we end up merging #11 then it's kinda moot.

2023-01-17 05:41 UTC, colinpcurtis commented
no more ping command #sad

2023-01-17 05:48 UTC, colinpcurtis approved these changes
looks good to me.  Testing is super great and this will really help the repo in the long term

2023-01-17 05:54 UTC, merged